// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from 'C:/Users/Administrator/LingmienAether/docs/docs/auto-neteasepaperdollrenderentity.md?type=frontmatter';
import { demoIndex as dmi0 } from 'C:/Users/Administrator/LingmienAether/docs/docs/auto-neteasepaperdollrenderentity.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from 'C:/Users/Administrator/LingmienAether/docs/docs/component-customplayerrender.md?type=frontmatter';
import { demoIndex as dmi1 } from 'C:/Users/Administrator/LingmienAether/docs/docs/component-customplayerrender.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from 'C:/Users/Administrator/LingmienAether/docs/docs/auto-customplayerrender.md?type=frontmatter';
import { demoIndex as dmi2 } from 'C:/Users/Administrator/LingmienAether/docs/docs/auto-customplayerrender.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from 'C:/Users/Administrator/LingmienAether/docs/docs/auto-custombossentity.md?type=frontmatter';
import { demoIndex as dmi3 } from 'C:/Users/Administrator/LingmienAether/docs/docs/auto-custombossentity.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from 'C:/Users/Administrator/LingmienAether/docs/docs/dlc-mianshen-config.md?type=frontmatter';
import { demoIndex as dmi4 } from 'C:/Users/Administrator/LingmienAether/docs/docs/dlc-mianshen-config.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from 'C:/Users/Administrator/LingmienAether/docs/docs/component-shootapi.md?type=frontmatter';
import { demoIndex as dmi5 } from 'C:/Users/Administrator/LingmienAether/docs/docs/component-shootapi.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from 'C:/Users/Administrator/LingmienAether/docs/docs/auto-lobbycontrol.md?type=frontmatter';
import { demoIndex as dmi6 } from 'C:/Users/Administrator/LingmienAether/docs/docs/auto-lobbycontrol.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from 'C:/Users/Administrator/LingmienAether/docs/docs/dlc_heixiyou_boss.md?type=frontmatter';
import { demoIndex as dmi7 } from 'C:/Users/Administrator/LingmienAether/docs/docs/dlc_heixiyou_boss.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from 'C:/Users/Administrator/LingmienAether/docs/docs/component-render.md?type=frontmatter';
import { demoIndex as dmi8 } from 'C:/Users/Administrator/LingmienAether/docs/docs/component-render.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/index.md?type=frontmatter';
import { demoIndex as dmi9 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/index.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_1_0/index.md?type=frontmatter';
import { demoIndex as dmi10 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_1_0/index.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from 'C:/Users/Administrator/LingmienAether/docs/docs/component-cyzs2.md?type=frontmatter';
import { demoIndex as dmi11 } from 'C:/Users/Administrator/LingmienAether/docs/docs/component-cyzs2.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/1010.md?type=frontmatter';
import { demoIndex as dmi12 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/1010.md?type=demo-index';
import { frontmatter as fm13, toc as t13 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/1011.md?type=frontmatter';
import { demoIndex as dmi13 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/1011.md?type=demo-index';
import { frontmatter as fm14, toc as t14 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/1012.md?type=frontmatter';
import { demoIndex as dmi14 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/1012.md?type=demo-index';
import { frontmatter as fm15, toc as t15 } from 'C:/Users/Administrator/LingmienAether/docs/docs/component-info.md?type=frontmatter';
import { demoIndex as dmi15 } from 'C:/Users/Administrator/LingmienAether/docs/docs/component-info.md?type=demo-index';
import { frontmatter as fm16, toc as t16 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/100.md?type=frontmatter';
import { demoIndex as dmi16 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/100.md?type=demo-index';
import { frontmatter as fm17, toc as t17 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/101.md?type=frontmatter';
import { demoIndex as dmi17 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/101.md?type=demo-index';
import { frontmatter as fm18, toc as t18 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/102.md?type=frontmatter';
import { demoIndex as dmi18 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/102.md?type=demo-index';
import { frontmatter as fm19, toc as t19 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/103.md?type=frontmatter';
import { demoIndex as dmi19 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/103.md?type=demo-index';
import { frontmatter as fm20, toc as t20 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/104.md?type=frontmatter';
import { demoIndex as dmi20 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/104.md?type=demo-index';
import { frontmatter as fm21, toc as t21 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/105.md?type=frontmatter';
import { demoIndex as dmi21 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/105.md?type=demo-index';
import { frontmatter as fm22, toc as t22 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/106.md?type=frontmatter';
import { demoIndex as dmi22 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/106.md?type=demo-index';
import { frontmatter as fm23, toc as t23 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/107.md?type=frontmatter';
import { demoIndex as dmi23 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/107.md?type=demo-index';
import { frontmatter as fm24, toc as t24 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/108.md?type=frontmatter';
import { demoIndex as dmi24 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/108.md?type=demo-index';
import { frontmatter as fm25, toc as t25 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/109.md?type=frontmatter';
import { demoIndex as dmi25 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/109.md?type=demo-index';
import { frontmatter as fm26, toc as t26 } from 'C:/Users/Administrator/LingmienAether/docs/docs/dlc-mianshen.md?type=frontmatter';
import { demoIndex as dmi26 } from 'C:/Users/Administrator/LingmienAether/docs/docs/dlc-mianshen.md?type=demo-index';
import { frontmatter as fm27, toc as t27 } from 'C:/Users/Administrator/LingmienAether/docs/files/demo/index.md?type=frontmatter';
import { demoIndex as dmi27 } from 'C:/Users/Administrator/LingmienAether/docs/files/demo/index.md?type=demo-index';
import { frontmatter as fm28, toc as t28 } from 'C:/Users/Administrator/LingmienAether/docs/docs/auto-sound.md?type=frontmatter';
import { demoIndex as dmi28 } from 'C:/Users/Administrator/LingmienAether/docs/docs/auto-sound.md?type=demo-index';
import { frontmatter as fm29, toc as t29 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/index.md?type=frontmatter';
import { demoIndex as dmi29 } from 'C:/Users/Administrator/LingmienAether/docs/downloads/index.md?type=demo-index';
import { frontmatter as fm30, toc as t30 } from 'C:/Users/Administrator/LingmienAether/docs/files/sfx/index.md?type=frontmatter';
import { demoIndex as dmi30 } from 'C:/Users/Administrator/LingmienAether/docs/files/sfx/index.md?type=demo-index';
import { frontmatter as fm31, toc as t31 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-10.md?type=frontmatter';
import { demoIndex as dmi31 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-10.md?type=demo-index';
import { frontmatter as fm32, toc as t32 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-11.md?type=frontmatter';
import { demoIndex as dmi32 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-11.md?type=demo-index';
import { frontmatter as fm33, toc as t33 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-12.md?type=frontmatter';
import { demoIndex as dmi33 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-12.md?type=demo-index';
import { frontmatter as fm34, toc as t34 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-13.md?type=frontmatter';
import { demoIndex as dmi34 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-13.md?type=demo-index';
import { frontmatter as fm35, toc as t35 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-14.md?type=frontmatter';
import { demoIndex as dmi35 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-14.md?type=demo-index';
import { frontmatter as fm36, toc as t36 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-15.md?type=frontmatter';
import { demoIndex as dmi36 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-15.md?type=demo-index';
import { frontmatter as fm37, toc as t37 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-16.md?type=frontmatter';
import { demoIndex as dmi37 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-16.md?type=demo-index';
import { frontmatter as fm38, toc as t38 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-17.md?type=frontmatter';
import { demoIndex as dmi38 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-17.md?type=demo-index';
import { frontmatter as fm39, toc as t39 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-18.md?type=frontmatter';
import { demoIndex as dmi39 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-18.md?type=demo-index';
import { frontmatter as fm40, toc as t40 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-19.md?type=frontmatter';
import { demoIndex as dmi40 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-19.md?type=demo-index';
import { frontmatter as fm41, toc as t41 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-20.md?type=frontmatter';
import { demoIndex as dmi41 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-20.md?type=demo-index';
import { frontmatter as fm42, toc as t42 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-21.md?type=frontmatter';
import { demoIndex as dmi42 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-21.md?type=demo-index';
import { frontmatter as fm43, toc as t43 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-22.md?type=frontmatter';
import { demoIndex as dmi43 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-22.md?type=demo-index';
import { frontmatter as fm44, toc as t44 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-23.md?type=frontmatter';
import { demoIndex as dmi44 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-23.md?type=demo-index';
import { frontmatter as fm45, toc as t45 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-24.md?type=frontmatter';
import { demoIndex as dmi45 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-24.md?type=demo-index';
import { frontmatter as fm46, toc as t46 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-25.md?type=frontmatter';
import { demoIndex as dmi46 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-25.md?type=demo-index';
import { frontmatter as fm47, toc as t47 } from 'C:/Users/Administrator/LingmienAether/docs/files/ui/index.md?type=frontmatter';
import { demoIndex as dmi47 } from 'C:/Users/Administrator/LingmienAether/docs/files/ui/index.md?type=demo-index';
import { frontmatter as fm48, toc as t48 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-1.md?type=frontmatter';
import { demoIndex as dmi48 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-1.md?type=demo-index';
import { frontmatter as fm49, toc as t49 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-2.md?type=frontmatter';
import { demoIndex as dmi49 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-2.md?type=demo-index';
import { frontmatter as fm50, toc as t50 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-3.md?type=frontmatter';
import { demoIndex as dmi50 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-3.md?type=demo-index';
import { frontmatter as fm51, toc as t51 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-4.md?type=frontmatter';
import { demoIndex as dmi51 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-4.md?type=demo-index';
import { frontmatter as fm52, toc as t52 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-5.md?type=frontmatter';
import { demoIndex as dmi52 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-5.md?type=demo-index';
import { frontmatter as fm53, toc as t53 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-6.md?type=frontmatter';
import { demoIndex as dmi53 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-6.md?type=demo-index';
import { frontmatter as fm54, toc as t54 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-7.md?type=frontmatter';
import { demoIndex as dmi54 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-7.md?type=demo-index';
import { frontmatter as fm55, toc as t55 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-8.md?type=frontmatter';
import { demoIndex as dmi55 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-8.md?type=demo-index';
import { frontmatter as fm56, toc as t56 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-9.md?type=frontmatter';
import { demoIndex as dmi56 } from 'C:/Users/Administrator/LingmienAether/docs/guides/guide-9.md?type=demo-index';
import { frontmatter as fm57, toc as t57 } from 'C:/Users/Administrator/LingmienAether/docs/docs/behavior.md?type=frontmatter';
import { demoIndex as dmi57 } from 'C:/Users/Administrator/LingmienAether/docs/docs/behavior.md?type=demo-index';
import { frontmatter as fm58, toc as t58 } from 'C:/Users/Administrator/LingmienAether/docs/docs/building.md?type=frontmatter';
import { demoIndex as dmi58 } from 'C:/Users/Administrator/LingmienAether/docs/docs/building.md?type=demo-index';
import { frontmatter as fm59, toc as t59 } from 'C:/Users/Administrator/LingmienAether/docs/docs/control.md?type=frontmatter';
import { demoIndex as dmi59 } from 'C:/Users/Administrator/LingmienAether/docs/docs/control.md?type=demo-index';
import { frontmatter as fm60, toc as t60 } from 'C:/Users/Administrator/LingmienAether/docs/docs/message.md?type=frontmatter';
import { demoIndex as dmi60 } from 'C:/Users/Administrator/LingmienAether/docs/docs/message.md?type=demo-index';
import { frontmatter as fm61, toc as t61 } from 'C:/Users/Administrator/LingmienAether/docs/updates/1010.md?type=frontmatter';
import { demoIndex as dmi61 } from 'C:/Users/Administrator/LingmienAether/docs/updates/1010.md?type=demo-index';
import { frontmatter as fm62, toc as t62 } from 'C:/Users/Administrator/LingmienAether/docs/updates/1011.md?type=frontmatter';
import { demoIndex as dmi62 } from 'C:/Users/Administrator/LingmienAether/docs/updates/1011.md?type=demo-index';
import { frontmatter as fm63, toc as t63 } from 'C:/Users/Administrator/LingmienAether/docs/updates/1012.md?type=frontmatter';
import { demoIndex as dmi63 } from 'C:/Users/Administrator/LingmienAether/docs/updates/1012.md?type=demo-index';
import { frontmatter as fm64, toc as t64 } from 'C:/Users/Administrator/LingmienAether/docs/updates/1013.md?type=frontmatter';
import { demoIndex as dmi64 } from 'C:/Users/Administrator/LingmienAether/docs/updates/1013.md?type=demo-index';
import { frontmatter as fm65, toc as t65 } from 'C:/Users/Administrator/LingmienAether/docs/docs/camera.md?type=frontmatter';
import { demoIndex as dmi65 } from 'C:/Users/Administrator/LingmienAether/docs/docs/camera.md?type=demo-index';
import { frontmatter as fm66, toc as t66 } from 'C:/Users/Administrator/LingmienAether/docs/docs/common.md?type=frontmatter';
import { demoIndex as dmi66 } from 'C:/Users/Administrator/LingmienAether/docs/docs/common.md?type=demo-index';
import { frontmatter as fm67, toc as t67 } from 'C:/Users/Administrator/LingmienAether/docs/docs/entity.md?type=frontmatter';
import { demoIndex as dmi67 } from 'C:/Users/Administrator/LingmienAether/docs/docs/entity.md?type=demo-index';
import { frontmatter as fm68, toc as t68 } from 'C:/Users/Administrator/LingmienAether/docs/docs/molang.md?type=frontmatter';
import { demoIndex as dmi68 } from 'C:/Users/Administrator/LingmienAether/docs/docs/molang.md?type=demo-index';
import { frontmatter as fm69, toc as t69 } from 'C:/Users/Administrator/LingmienAether/docs/docs/player.md?type=frontmatter';
import { demoIndex as dmi69 } from 'C:/Users/Administrator/LingmienAether/docs/docs/player.md?type=demo-index';
import { frontmatter as fm70, toc as t70 } from 'C:/Users/Administrator/LingmienAether/docs/files/index.md?type=frontmatter';
import { demoIndex as dmi70 } from 'C:/Users/Administrator/LingmienAether/docs/files/index.md?type=demo-index';
import { frontmatter as fm71, toc as t71 } from 'C:/Users/Administrator/LingmienAether/docs/updates/100.md?type=frontmatter';
import { demoIndex as dmi71 } from 'C:/Users/Administrator/LingmienAether/docs/updates/100.md?type=demo-index';
import { frontmatter as fm72, toc as t72 } from 'C:/Users/Administrator/LingmienAether/docs/updates/101.md?type=frontmatter';
import { demoIndex as dmi72 } from 'C:/Users/Administrator/LingmienAether/docs/updates/101.md?type=demo-index';
import { frontmatter as fm73, toc as t73 } from 'C:/Users/Administrator/LingmienAether/docs/updates/102.md?type=frontmatter';
import { demoIndex as dmi73 } from 'C:/Users/Administrator/LingmienAether/docs/updates/102.md?type=demo-index';
import { frontmatter as fm74, toc as t74 } from 'C:/Users/Administrator/LingmienAether/docs/updates/103.md?type=frontmatter';
import { demoIndex as dmi74 } from 'C:/Users/Administrator/LingmienAether/docs/updates/103.md?type=demo-index';
import { frontmatter as fm75, toc as t75 } from 'C:/Users/Administrator/LingmienAether/docs/updates/104.md?type=frontmatter';
import { demoIndex as dmi75 } from 'C:/Users/Administrator/LingmienAether/docs/updates/104.md?type=demo-index';
import { frontmatter as fm76, toc as t76 } from 'C:/Users/Administrator/LingmienAether/docs/updates/105.md?type=frontmatter';
import { demoIndex as dmi76 } from 'C:/Users/Administrator/LingmienAether/docs/updates/105.md?type=demo-index';
import { frontmatter as fm77, toc as t77 } from 'C:/Users/Administrator/LingmienAether/docs/updates/106.md?type=frontmatter';
import { demoIndex as dmi77 } from 'C:/Users/Administrator/LingmienAether/docs/updates/106.md?type=demo-index';
import { frontmatter as fm78, toc as t78 } from 'C:/Users/Administrator/LingmienAether/docs/updates/107.md?type=frontmatter';
import { demoIndex as dmi78 } from 'C:/Users/Administrator/LingmienAether/docs/updates/107.md?type=demo-index';
import { frontmatter as fm79, toc as t79 } from 'C:/Users/Administrator/LingmienAether/docs/updates/108.md?type=frontmatter';
import { demoIndex as dmi79 } from 'C:/Users/Administrator/LingmienAether/docs/updates/108.md?type=demo-index';
import { frontmatter as fm80, toc as t80 } from 'C:/Users/Administrator/LingmienAether/docs/updates/109.md?type=frontmatter';
import { demoIndex as dmi80 } from 'C:/Users/Administrator/LingmienAether/docs/updates/109.md?type=demo-index';
import { frontmatter as fm81, toc as t81 } from 'C:/Users/Administrator/LingmienAether/docs/updates/110.md?type=frontmatter';
import { demoIndex as dmi81 } from 'C:/Users/Administrator/LingmienAether/docs/updates/110.md?type=demo-index';
import { frontmatter as fm82, toc as t82 } from 'C:/Users/Administrator/LingmienAether/docs/docs/block.md?type=frontmatter';
import { demoIndex as dmi82 } from 'C:/Users/Administrator/LingmienAether/docs/docs/block.md?type=demo-index';
import { frontmatter as fm83, toc as t83 } from 'C:/Users/Administrator/LingmienAether/docs/docs/items.md?type=frontmatter';
import { demoIndex as dmi83 } from 'C:/Users/Administrator/LingmienAether/docs/docs/items.md?type=demo-index';
import { frontmatter as fm84, toc as t84 } from 'C:/Users/Administrator/LingmienAether/docs/docs/lobby.md?type=frontmatter';
import { demoIndex as dmi84 } from 'C:/Users/Administrator/LingmienAether/docs/docs/lobby.md?type=demo-index';
import { frontmatter as fm85, toc as t85 } from 'C:/Users/Administrator/LingmienAether/docs/docs/model.md?type=frontmatter';
import { demoIndex as dmi85 } from 'C:/Users/Administrator/LingmienAether/docs/docs/model.md?type=demo-index';
import { frontmatter as fm86, toc as t86 } from 'C:/Users/Administrator/LingmienAether/docs/docs/sound.md?type=frontmatter';
import { demoIndex as dmi86 } from 'C:/Users/Administrator/LingmienAether/docs/docs/sound.md?type=demo-index';
import { frontmatter as fm87, toc as t87 } from 'C:/Users/Administrator/LingmienAether/docs/docs/data.md?type=frontmatter';
import { demoIndex as dmi87 } from 'C:/Users/Administrator/LingmienAether/docs/docs/data.md?type=demo-index';
import { frontmatter as fm88, toc as t88 } from 'C:/Users/Administrator/LingmienAether/docs/docs/info.md?type=frontmatter';
import { demoIndex as dmi88 } from 'C:/Users/Administrator/LingmienAether/docs/docs/info.md?type=demo-index';
import { frontmatter as fm89, toc as t89 } from 'C:/Users/Administrator/LingmienAether/docs/docs/all.md?type=frontmatter';
import { demoIndex as dmi89 } from 'C:/Users/Administrator/LingmienAether/docs/docs/all.md?type=demo-index';
import { frontmatter as fm90, toc as t90 } from 'C:/Users/Administrator/LingmienAether/docs/docs/sfx.md?type=frontmatter';
import { demoIndex as dmi90 } from 'C:/Users/Administrator/LingmienAether/docs/docs/sfx.md?type=demo-index';
import { frontmatter as fm91, toc as t91 } from 'C:/Users/Administrator/LingmienAether/docs/docs/ui.md?type=frontmatter';
import { demoIndex as dmi91 } from 'C:/Users/Administrator/LingmienAether/docs/docs/ui.md?type=demo-index';
import { frontmatter as fm92, toc as t92 } from 'C:/Users/Administrator/LingmienAether/docs/index.md?type=frontmatter';
import { demoIndex as dmi92 } from 'C:/Users/Administrator/LingmienAether/docs/index.md?type=demo-index';

export const filesMeta = {
  'docs/docs/auto-neteasepaperdollrenderentity': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/auto-neteasepaperdollrenderentity.md?type=text'),
  },
  'docs/docs/component-customplayerrender': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/component-customplayerrender.md?type=text'),
  },
  'docs/docs/auto-customplayerrender': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/auto-customplayerrender.md?type=text'),
  },
  'docs/docs/auto-custombossentity': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/auto-custombossentity.md?type=text'),
  },
  'docs/docs/dlc-mianshen-config': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/dlc-mianshen-config.md?type=text'),
  },
  'docs/docs/component-shootapi': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/component-shootapi.md?type=text'),
  },
  'docs/docs/auto-lobbycontrol': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/auto-lobbycontrol.md?type=text'),
  },
  'docs/docs/dlc_heixiyou_boss': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/dlc_heixiyou_boss.md?type=text'),
  },
  'docs/docs/component-render': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/component-render.md?type=text'),
  },
  'docs/downloads/1_0_x/index': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/index.md?type=text'),
  },
  'docs/downloads/1_1_0/index': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_1_0/index.md?type=text'),
  },
  'docs/docs/component-cyzs2': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/component-cyzs2.md?type=text'),
  },
  'docs/downloads/1_0_x/1010': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/1010.md?type=text'),
  },
  'docs/downloads/1_0_x/1011': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/1011.md?type=text'),
  },
  'docs/downloads/1_0_x/1012': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/1012.md?type=text'),
  },
  'docs/docs/component-info': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/component-info.md?type=text'),
  },
  'docs/downloads/1_0_x/100': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/100.md?type=text'),
  },
  'docs/downloads/1_0_x/101': {
    frontmatter: fm17,
    toc: t17,
    demoIndex: dmi17,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/101.md?type=text'),
  },
  'docs/downloads/1_0_x/102': {
    frontmatter: fm18,
    toc: t18,
    demoIndex: dmi18,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/102.md?type=text'),
  },
  'docs/downloads/1_0_x/103': {
    frontmatter: fm19,
    toc: t19,
    demoIndex: dmi19,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/103.md?type=text'),
  },
  'docs/downloads/1_0_x/104': {
    frontmatter: fm20,
    toc: t20,
    demoIndex: dmi20,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/104.md?type=text'),
  },
  'docs/downloads/1_0_x/105': {
    frontmatter: fm21,
    toc: t21,
    demoIndex: dmi21,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/105.md?type=text'),
  },
  'docs/downloads/1_0_x/106': {
    frontmatter: fm22,
    toc: t22,
    demoIndex: dmi22,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/106.md?type=text'),
  },
  'docs/downloads/1_0_x/107': {
    frontmatter: fm23,
    toc: t23,
    demoIndex: dmi23,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/107.md?type=text'),
  },
  'docs/downloads/1_0_x/108': {
    frontmatter: fm24,
    toc: t24,
    demoIndex: dmi24,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/108.md?type=text'),
  },
  'docs/downloads/1_0_x/109': {
    frontmatter: fm25,
    toc: t25,
    demoIndex: dmi25,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/1_0_x/109.md?type=text'),
  },
  'docs/docs/dlc-mianshen': {
    frontmatter: fm26,
    toc: t26,
    demoIndex: dmi26,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/dlc-mianshen.md?type=text'),
  },
  'docs/files/demo/index': {
    frontmatter: fm27,
    toc: t27,
    demoIndex: dmi27,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/files/demo/index.md?type=text'),
  },
  'docs/docs/auto-sound': {
    frontmatter: fm28,
    toc: t28,
    demoIndex: dmi28,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/auto-sound.md?type=text'),
  },
  'docs/downloads/index': {
    frontmatter: fm29,
    toc: t29,
    demoIndex: dmi29,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/downloads/index.md?type=text'),
  },
  'docs/files/sfx/index': {
    frontmatter: fm30,
    toc: t30,
    demoIndex: dmi30,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/files/sfx/index.md?type=text'),
  },
  'docs/guides/guide-10': {
    frontmatter: fm31,
    toc: t31,
    demoIndex: dmi31,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-10.md?type=text'),
  },
  'docs/guides/guide-11': {
    frontmatter: fm32,
    toc: t32,
    demoIndex: dmi32,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-11.md?type=text'),
  },
  'docs/guides/guide-12': {
    frontmatter: fm33,
    toc: t33,
    demoIndex: dmi33,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-12.md?type=text'),
  },
  'docs/guides/guide-13': {
    frontmatter: fm34,
    toc: t34,
    demoIndex: dmi34,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-13.md?type=text'),
  },
  'docs/guides/guide-14': {
    frontmatter: fm35,
    toc: t35,
    demoIndex: dmi35,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-14.md?type=text'),
  },
  'docs/guides/guide-15': {
    frontmatter: fm36,
    toc: t36,
    demoIndex: dmi36,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-15.md?type=text'),
  },
  'docs/guides/guide-16': {
    frontmatter: fm37,
    toc: t37,
    demoIndex: dmi37,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-16.md?type=text'),
  },
  'docs/guides/guide-17': {
    frontmatter: fm38,
    toc: t38,
    demoIndex: dmi38,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-17.md?type=text'),
  },
  'docs/guides/guide-18': {
    frontmatter: fm39,
    toc: t39,
    demoIndex: dmi39,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-18.md?type=text'),
  },
  'docs/guides/guide-19': {
    frontmatter: fm40,
    toc: t40,
    demoIndex: dmi40,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-19.md?type=text'),
  },
  'docs/guides/guide-20': {
    frontmatter: fm41,
    toc: t41,
    demoIndex: dmi41,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-20.md?type=text'),
  },
  'docs/guides/guide-21': {
    frontmatter: fm42,
    toc: t42,
    demoIndex: dmi42,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-21.md?type=text'),
  },
  'docs/guides/guide-22': {
    frontmatter: fm43,
    toc: t43,
    demoIndex: dmi43,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-22.md?type=text'),
  },
  'docs/guides/guide-23': {
    frontmatter: fm44,
    toc: t44,
    demoIndex: dmi44,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-23.md?type=text'),
  },
  'docs/guides/guide-24': {
    frontmatter: fm45,
    toc: t45,
    demoIndex: dmi45,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-24.md?type=text'),
  },
  'docs/guides/guide-25': {
    frontmatter: fm46,
    toc: t46,
    demoIndex: dmi46,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-25.md?type=text'),
  },
  'docs/files/ui/index': {
    frontmatter: fm47,
    toc: t47,
    demoIndex: dmi47,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/files/ui/index.md?type=text'),
  },
  'docs/guides/guide-1': {
    frontmatter: fm48,
    toc: t48,
    demoIndex: dmi48,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-1.md?type=text'),
  },
  'docs/guides/guide-2': {
    frontmatter: fm49,
    toc: t49,
    demoIndex: dmi49,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-2.md?type=text'),
  },
  'docs/guides/guide-3': {
    frontmatter: fm50,
    toc: t50,
    demoIndex: dmi50,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-3.md?type=text'),
  },
  'docs/guides/guide-4': {
    frontmatter: fm51,
    toc: t51,
    demoIndex: dmi51,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-4.md?type=text'),
  },
  'docs/guides/guide-5': {
    frontmatter: fm52,
    toc: t52,
    demoIndex: dmi52,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-5.md?type=text'),
  },
  'docs/guides/guide-6': {
    frontmatter: fm53,
    toc: t53,
    demoIndex: dmi53,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-6.md?type=text'),
  },
  'docs/guides/guide-7': {
    frontmatter: fm54,
    toc: t54,
    demoIndex: dmi54,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-7.md?type=text'),
  },
  'docs/guides/guide-8': {
    frontmatter: fm55,
    toc: t55,
    demoIndex: dmi55,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-8.md?type=text'),
  },
  'docs/guides/guide-9': {
    frontmatter: fm56,
    toc: t56,
    demoIndex: dmi56,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/guides/guide-9.md?type=text'),
  },
  'docs/docs/behavior': {
    frontmatter: fm57,
    toc: t57,
    demoIndex: dmi57,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/behavior.md?type=text'),
  },
  'docs/docs/building': {
    frontmatter: fm58,
    toc: t58,
    demoIndex: dmi58,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/building.md?type=text'),
  },
  'docs/docs/control': {
    frontmatter: fm59,
    toc: t59,
    demoIndex: dmi59,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/control.md?type=text'),
  },
  'docs/docs/message': {
    frontmatter: fm60,
    toc: t60,
    demoIndex: dmi60,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/message.md?type=text'),
  },
  'docs/updates/1010': {
    frontmatter: fm61,
    toc: t61,
    demoIndex: dmi61,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/1010.md?type=text'),
  },
  'docs/updates/1011': {
    frontmatter: fm62,
    toc: t62,
    demoIndex: dmi62,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/1011.md?type=text'),
  },
  'docs/updates/1012': {
    frontmatter: fm63,
    toc: t63,
    demoIndex: dmi63,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/1012.md?type=text'),
  },
  'docs/updates/1013': {
    frontmatter: fm64,
    toc: t64,
    demoIndex: dmi64,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/1013.md?type=text'),
  },
  'docs/docs/camera': {
    frontmatter: fm65,
    toc: t65,
    demoIndex: dmi65,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/camera.md?type=text'),
  },
  'docs/docs/common': {
    frontmatter: fm66,
    toc: t66,
    demoIndex: dmi66,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/common.md?type=text'),
  },
  'docs/docs/entity': {
    frontmatter: fm67,
    toc: t67,
    demoIndex: dmi67,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/entity.md?type=text'),
  },
  'docs/docs/molang': {
    frontmatter: fm68,
    toc: t68,
    demoIndex: dmi68,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/molang.md?type=text'),
  },
  'docs/docs/player': {
    frontmatter: fm69,
    toc: t69,
    demoIndex: dmi69,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/player.md?type=text'),
  },
  'docs/files/index': {
    frontmatter: fm70,
    toc: t70,
    demoIndex: dmi70,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/files/index.md?type=text'),
  },
  'docs/updates/100': {
    frontmatter: fm71,
    toc: t71,
    demoIndex: dmi71,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/100.md?type=text'),
  },
  'docs/updates/101': {
    frontmatter: fm72,
    toc: t72,
    demoIndex: dmi72,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/101.md?type=text'),
  },
  'docs/updates/102': {
    frontmatter: fm73,
    toc: t73,
    demoIndex: dmi73,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/102.md?type=text'),
  },
  'docs/updates/103': {
    frontmatter: fm74,
    toc: t74,
    demoIndex: dmi74,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/103.md?type=text'),
  },
  'docs/updates/104': {
    frontmatter: fm75,
    toc: t75,
    demoIndex: dmi75,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/104.md?type=text'),
  },
  'docs/updates/105': {
    frontmatter: fm76,
    toc: t76,
    demoIndex: dmi76,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/105.md?type=text'),
  },
  'docs/updates/106': {
    frontmatter: fm77,
    toc: t77,
    demoIndex: dmi77,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/106.md?type=text'),
  },
  'docs/updates/107': {
    frontmatter: fm78,
    toc: t78,
    demoIndex: dmi78,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/107.md?type=text'),
  },
  'docs/updates/108': {
    frontmatter: fm79,
    toc: t79,
    demoIndex: dmi79,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/108.md?type=text'),
  },
  'docs/updates/109': {
    frontmatter: fm80,
    toc: t80,
    demoIndex: dmi80,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/109.md?type=text'),
  },
  'docs/updates/110': {
    frontmatter: fm81,
    toc: t81,
    demoIndex: dmi81,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/updates/110.md?type=text'),
  },
  'docs/docs/block': {
    frontmatter: fm82,
    toc: t82,
    demoIndex: dmi82,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/block.md?type=text'),
  },
  'docs/docs/items': {
    frontmatter: fm83,
    toc: t83,
    demoIndex: dmi83,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/items.md?type=text'),
  },
  'docs/docs/lobby': {
    frontmatter: fm84,
    toc: t84,
    demoIndex: dmi84,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/lobby.md?type=text'),
  },
  'docs/docs/model': {
    frontmatter: fm85,
    toc: t85,
    demoIndex: dmi85,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/model.md?type=text'),
  },
  'docs/docs/sound': {
    frontmatter: fm86,
    toc: t86,
    demoIndex: dmi86,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/sound.md?type=text'),
  },
  'docs/docs/data': {
    frontmatter: fm87,
    toc: t87,
    demoIndex: dmi87,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/data.md?type=text'),
  },
  'docs/docs/info': {
    frontmatter: fm88,
    toc: t88,
    demoIndex: dmi88,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/info.md?type=text'),
  },
  'docs/docs/all': {
    frontmatter: fm89,
    toc: t89,
    demoIndex: dmi89,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/all.md?type=text'),
  },
  'docs/docs/sfx': {
    frontmatter: fm90,
    toc: t90,
    demoIndex: dmi90,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/sfx.md?type=text'),
  },
  'docs/docs/ui': {
    frontmatter: fm91,
    toc: t91,
    demoIndex: dmi91,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/docs/ui.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm92,
    toc: t92,
    demoIndex: dmi92,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/Administrator/LingmienAether/docs/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
